### ISSUE TITLE
Pretraining weights for the non-vision task?

### ISSUE THREAD

**Issue by spencer-hong** [microsoft/i-Code#10]
Hi, based on the paper, it sounded like there would be a release of the pretraining weights for the text and layout pretraining tasks for UDOP. When will that be released? Thanks!

**Comment by ziyi-yang** [comment]
Hello, we appreciate your interest in our work. We will release the pretraining weight shortly. Will update here once done.

**Comment by zinengtang** [comment]
We will release it this/next week at latest.

**Comment by WaterKnight1998** [comment]
Thank you very much for the effort @zinengtang
