### ISSUE TITLE
Img2Img Broken?

### ISSUE THREAD

**Issue by jacklishufan** [microsoft/i-Code#116]
Hi thanks for the great work.
While this is not explored in paper, but since the conditions are aligned, in principle it should be possible to perform img2img task to encode an image and decode the latent to a similar image (at least in some aspect)? 
However simple experiments show this fails
<img width="703" alt="image" src="https://github.com/microsoft/i-Code/assets/17161214/e359f564-f32a-4fbb-833a-1ecd533a7467">

I was expecting it to behave like DALLE-2's UNCLIP decoder. Any idea why this does not work? Are you applying some special attention map so that one modality do not attend to inputs of same modality?

**Comment by zinengtang** [comment]
I think this might be the issue for transformer version. What version you are currently using. Did you run pip install -r requirement.txt?
