### ISSUE TITLE
Can you provide classifier-free guidance probability?

### ISSUE THREAD

**Issue by jaykim9870** [microsoft/i-Code#119]
Hi, I am looking for the training and sampling details of your model, and I couldn't find the probability of dropping condition for the classifier-free guidance.

Could you provide the classifier-free guidance probability? I am wondering if you used the 10% as Stable Diffusion or differently?

Thank you so much for your great work and effort.

**Comment by zinengtang** [comment]
I am using 10% during training. But since we haven't provided the training code (which might needs approval if there is a high demand), it is not provided in the code.
