### ISSUE TITLE
 Document Understanding

### ISSUE THREAD

**Issue by BakingBrains** [microsoft/i-Code#13]
For the DocVQA, does UDOP follow the same procedure as layoutLM (single image input) or can we can do it in a document level. For example given an input of document with 15 pages and performing DocVQA on that.

**Comment by zinengtang** [comment]
Doing multipages are generally easy for Udop by concatenating the images and adding page id embedding or biases. But too large number of pages will be a memory issue. But currently, we haven't implemented multi-page.

**Comment by ziyi-yang** [comment]
Close for now. Feel free to re-open if there's follow-up question on multi-page processing.
