### ISSUE TITLE
Missing import for DropPath in mae.py

### ISSUE THREAD

**Issue by IrinaArmstrong** [microsoft/i-Code#14]
Hello!

Started going through the code and found that _mae.py_ file is missing the import line for _DropPath_ class.
As I understood, it was taken from the _timm_ library, that is something like this is missed:

`from timm.models.layers.drop import DropPath`

**Comment by cwl520wwh** [comment]
> Hello!
> 
> Started going through the code and found that _mae.py_ file is missing the import line for _DropPath_ class. As I understood, it was taken from the _timm_ library, that is something like this is missed:
> 
> `from timm.models.layers.drop import DropPath`
 have you solve the problem?
