### ISSUE TITLE
Question about tokenizer and config.json

### ISSUE THREAD

**Issue by maxjeblick** [microsoft/i-Code#17]
Hi,

I noticed that the files contained in https://huggingface.co/ZinengTang/Udop/tree/main contain the model weights (`pytorch_model.bin` for `UdopDual-Large-224` and `UdopUnimodel-Large-224`), but not `config.json` or tokenizer related files.
Are those missing files identical to `t5-large`?

Thanks!

**Comment by zinengtang** [comment]
Yeah the configurations should be identical to t5 (tokenizer) or can be initialized by default parameters.
We will add our own configuration files when we add the model to Huggingface Transformer.

**Comment by raghavanone** [comment]
@zinengtang I am trying to add the model to huggingface [here ](https://github.com/huggingface/transformers/pull/21239) . But the model weights are incomplete with out vision decoder weights.

**Comment by logan-markewich** [comment]
@raghavanone according to the README, the vision decoder weights will only be released as part of an azure API. Therefore, not exactly openly available.

**Comment by maxjeblick** [comment]
It's still unclear to me how to use the model.
I tried initializing as 
```
import torch

from core.models import UdopDualForConditionalGeneration, UdopUnimodelForConditionalGeneration, UdopConfig, \
    UdopTokenizer

MODEL_CLASSES = {
    'UdopDual': (UdopConfig, UdopDualForConditionalGeneration, UdopTokenizer),
    'UdopUnimodel': (UdopConfig, UdopUnimodelForConditionalGeneration, UdopTokenizer),
}

config = UdopConfig.from_pretrained("t5-large")
# also tried config = AutoConfig.from_pretrained("t5-large")

tokenizer = UdopTokenizer.from_pretrained("t5-large")
model = UdopUnimodelForConditionalGeneration.from_pretrained("t5-large")
model.load_state_dict(
    torch.load("models/UdopUnimodel-Large-224/pytorch_model.bin"))
```
which gives

`AttributeError: 'T5Config' object has no attribute 'truncate_encoder_after_layer'`

**Comment by go2carter** [comment]
I fixed that by fixed the lines in "udop_dual.py" and "udop_unimodel.py" to:
```
        if self.is_decoder:
            self.num_layers = (
                config.truncate_decoder_after_layer
                    if (hasattr(config, 'truncate_decoder_after_layer') and config.truncate_decoder_after_layer)
                    else config.num_layers
            )
        else:
            self.num_layers = (
                config.truncate_encoder_after_layer
                    if (hasattr(config, 'truncate_encoder_after_layer') and config.truncate_encoder_after_layer)
                    else config.num_layers
            )
```

**Comment by go2carter** [comment]
but then I run into the following error for both models:
`AttributeError: 'UdopConfig' object has no attribute 'data_dir'`

**Comment by ziyi-yang** [comment]
> 

Right the current checkpoint doesn't contain the vision decoder part. We are still in the discussion of the most appropriate way of open sourcing that part.

**Comment by ziyi-yang** [comment]
> It's still unclear to me how to use the model. I tried initializing as
> 
> ```
> import torch
> 
> from core.models import UdopDualForConditionalGeneration, UdopUnimodelForConditionalGeneration, UdopConfig, \
>     UdopTokenizer
> 
> MODEL_CLASSES = {
>     'UdopDual': (UdopConfig, UdopDualForConditionalGeneration, UdopTokenizer),
>     'UdopUnimodel': (UdopConfig, UdopUnimodelForConditionalGeneration, UdopTokenizer),
> }
> 
> config = UdopConfig.from_pretrained("t5-large")
> # also tried config = AutoConfig.from_pretrained("t5-large")
> 
> tokenizer = UdopTokenizer.from_pretrained("t5-large")
> model = UdopUnimodelForConditionalGeneration.from_pretrained("t5-large")
> # also tried model = UdopUnimodelForConditionalGeneration(config)
> model.load_state_dict(
>     torch.load("models/UdopUnimodel-Large-224/pytorch_model.bin"))
> ```
> 
> which gives
> 
> `AttributeError: 'T5Config' object has no attribute 'truncate_encoder_after_layer'`

@zinengtang Can you take a look at this?

**Comment by go2carter** [comment]
> > 
> 
> Right the current checkpoint doesn't contain the vision decoder part. We are still in the discussion of the most appropriate way of open sourcing that part.

I see. We should be able to run inference then still with the provided model weights--correct?

**Comment by ziyi-yang** [comment]
Yes, running inference with the provided model weights is doable.

**Comment by go2carter** [comment]
I've also been having trouble loading the model to test it out. When I tried, @maxjeblick 's code above with my fixes, then I get: `AttributeError: 'T5Config' object has no attribute 'max_2d_position_embeddings'`

**Comment by logan-markewich** [comment]
You might have to add a few keys to the config manually. Check out the values from [this config](https://github.com/huggingface/transformers/pull/21239/commits/a5fb2c7bba542c6c0eb7131d1480b1ae0a55c819#diff-1853643703abf14161eef5846c305d77e4bedb8e81650eeb8cdc87477effbfd2)

This is from the PR to add the model to huggingface. Unless you are in a rush, it might be best to wait for the model to be added to huggingface. Everything will work much smoother then :)

**Comment by go2carter** [comment]
@logan-markewich 
Thank you! I'll try that out when I get the opportunity. Not in a rush, but I'm excited to try out this work :)

**Comment by ziyi-yang** [comment]
Thanks again for your great interest in our work, also we appreciate huggingface team's efforts. We'll fix the issue on our side ASAP.

**Comment by zinengtang** [comment]
I have made a PR on fixing the issues and updated the model checkpoint to huggingface style checkpoints/configs. Let me know if the issue is still not addressed.

**Comment by maxjeblick** [comment]
Thanks for the fix!
I tested `udop-dual-large-224` with the code below (where I have downloaded model weights before), and it now works.

```
from core.models import UdopDualForConditionalGeneration, UdopUnimodelForConditionalGeneration, UdopConfig, \
    UdopTokenizer


config = UdopConfig.from_pretrained("../udop-dual-large-224")
tokenizer = UdopTokenizer.from_pretrained("../udop-dual-large-224")
model = UdopDualForConditionalGeneration.from_pretrained("../udop-dual-large-224")
```

**Comment by go2carter** [comment]
awesome! Excited to try it out when I get a chance
