### ISSUE TITLE
DocVQA

### ISSUE THREAD

**Issue by shamanthak-hegde** [microsoft/i-Code#18]
Hi,
I see that the fine_rvlcdip.sh is used to train on the classification dataset from scratch. What's the procedure to train the model on DocVQA task from scratch?
Also what does the finetune_duebenchmark.sh exactly do? I couldn't run it because it required the config file for the pretrained model which is not available yet.

Thanks!!!

**Comment by logan-markewich** [comment]
DUE benchmark is a benchmark of tasks, which includes DocVQA among other things. Its used to evaluate document understanding models

https://duebenchmark.com/leaderboard

**Comment by shamanthak-hegde** [comment]
Is there a way to train the model from scratch on DocVQA in the given codes?

**Comment by logan-markewich** [comment]
Not exactly in the given codes, you will have to read the due_benchmark code and write some custom training from there.

Personally, I would wait until the model is [added to huggingface ](https://github.com/huggingface/transformers/pull/21239) in the coming weeks. Training will be much more straightforward then
