### ISSUE TITLE
‘UdopUnimodelForConditionalGeneration' object has no attribute 'special_vis_token'

### ISSUE THREAD

**Issue by rr191211** [microsoft/i-Code#21]
I ran your finetune_duebenchmark.sh script to finetune DocVQA dataset，but got an error as below:
<img width="938" alt="bug" src="https://user-images.githubusercontent.com/105635332/218096603-4ae078fd-91c6-47cb-9420-7472fb1dbeaa.png">
how to handle it? Thanks for your help.

**Comment by zinengtang** [comment]
For now you can refer to this PR before it is merged.

**Comment by ziyi-yang** [comment]
PR #22 is merged.

**Comment by rr191211** [comment]
It works, Thank you!
