### ISSUE TITLE
Unresolved reference

### ISSUE THREAD

**Issue by aiPenguin** [microsoft/i-Code#26]
Hi,

Firstly, thanks a lot for your awesome work!

There seems to be some errors in run_rvlcdip.py file. In the line "from datasets import ClassLabel, load_dataset, load_metric" it shows "Unresolved reference 'datasets'". And I can't find a module named datasets in the project folder.

Best regards,

**Comment by logan-markewich** [comment]
It looks like there's a missed library in the requirements 

Just run "pip install datasets", it's a very popular library from huggingface 👍🏻

**Comment by aiPenguin** [comment]
Oh, I see. Thanks!
