### ISSUE TITLE
Demos on actual documents

### ISSUE THREAD

**Issue by thefirebanks** [microsoft/i-Code#32]
Hello! Thank you for making this available - I was wondering if there are any demos that you could share where text/information is extracted from a PDF? I have seen that the current scripts uploaded are for fine-tuning, but it would be nice to have a script for just inference on new docs! Thank you

**Comment by zinengtang** [comment]
refer to this PR https://github.com/microsoft/i-Code/pull/36 for more details/demo before it is merged.
