### ISSUE TITLE
Can the provided models perform multi-label classification?

### ISSUE THREAD

**Issue by plamb-viso** [microsoft/i-Code#33]
The provided code examples provide a good example of single label classification (e.g. rvlcdip). But can this be easily extended to multi-label classification? I'm a bit new to models where the predicted label is the actual textual representation of the label versus an integer. In the latter case multi-label can be provided through one-hot encoding an array of possible labels; does UDOP have a similar extension from single label to multi-label? How would one do it?

**Comment by logan-markewich** [comment]
For multi label (and single!) I think the general approach is to add special tokens to the tokenizer (I.e. `<CLASS_2/>`) and train the model to predict the relevant class tokens for each input

**Comment by zinengtang** [comment]
We are a generative open vocabulary model so the answer should be yes. We have a text decoder to generate text so there is no reason UDOP can't generate text.
