### ISSUE TITLE
Document-parsing example

### ISSUE THREAD

**Issue by WaterKnight1998** [microsoft/i-Code#35]
Good morning,

First off all, thank you very much for open sourcing this model.

I have been looking at this model as an alternative to [Donut](https://github.com/clovaai/donut) for Document Parsing, I think we will get better performance as OCR data is included.

However, after checking your repository I just saw scripts for document classification and understanding. An example for  Document Parsing or token classification will be helpfull. For document parsing I mean an example similar to this [one](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/Donut/CORD/Fine_tune_Donut_on_a_custom_dataset_(CORD)_with_PyTorch_Lightning.ipynb)  for CORD dataset.

Thanks in advance! @zinengtang @ziyi-yang 

Best regards

**Comment by ziyi-yang** [comment]
Thanks again for your interest in our work. Here's an example of how UDOP works on an actual document: https://github.com/microsoft/i-Code/blob/main/i-Code-Doc/example_io.ipynb

Thanks.

**Comment by thinh-huynh-re** [comment]
Hi @ziyi-yang , thank you for your amazing works.
I follow the notebook with `task_prefix = 'document classification'`, it outputs the final result as expected `form`
However, when I change the `task_prefix = 'layout analysis'`, it still outputs `form` 
So, Is the model only trained for one downstream task `document classification` ?
(More information, I use the model `udop-unimodel-large-224` downloaded from https://huggingface.co/ZinengTang/Udop)

**Comment by glahoti6** [comment]
I have a question same as @thinh-huynh-re. Could someone help us with that?
Also, how to generate 00070353.json in the examples folder of i-Code-Doc?
