### ISSUE TITLE
Poor performance on various tasks using the provided example

### ISSUE THREAD

**Issue by mike-grayhat** [microsoft/i-Code#46]
Hi, thanks for publishing the model and its weights - it looks very promising. Sadly I can't get good results out of it using the provided notebook. For example if I ask more complex questions (which it should support due to pretraining as far as I understand), it fails to produce correct answers. 
Let's say I modify the prompt to `task_prefix = "Layout Modeling. <layout_0> Manuscript </layout_0> review"` - the model gives me `'form'`, which is incorrect, and I get in most cases either "form" or some other incorrect answer. For `task_prefix = 'information extraction. What is the completion date?'` it gives me `'3/16/68'` which is close but still incorrect. Can you provide more elaborate examples with different task prompts so it will be possible to check if it's something on my side or if there is a problem with the model?

**Comment by ziyi-yang** [comment]
To obtain the best performance of CoDi, finetuning is recommended. Zero-shot QA or IE of UDOP still needs improvement.

**Comment by mczhuge** [comment]
When I fed some very simple images for image-to-text, the descriptions cannot capture any useful information about the images and show randomly descriptions. But the performance recorded (Table 5) in the paper is not so bad. Do you have some suggestions?

**Comment by zinengtang** [comment]
Can you give me some examples of the generation?

**Comment by mczhuge** [comment]
<img width="805" alt="image" src="https://github.com/microsoft/i-Code/assets/64179323/24530237-b5d9-4051-ba44-0d1318f543d6">

Just see this example, the caption is useless. And this is not cherry-pick failure case, nearly all samples are failed to generate common captions.

Please check. And feel free to tell me if I miss anything.

**Comment by mczhuge** [comment]
Besides, all the generated audio are noises.

**Comment by ziyi-yang** [comment]
> Besides, all the generated audio are noises.

For audio generation, can you double check the audio LMD checkpoint is loaded? Similar to this issue here: https://github.com/microsoft/i-Code/issues/57

`model_load_paths = ['CoDi_encoders.pth', 'CoDi_text_diffuser.pth', 'CoDi_video_diffuser_8frames.pth', 'CoDi_audio_diffuser_m.pth']`

**Comment by zinengtang** [comment]
@mczhuge @ziyi-yang I think I just found out the issue. There is an probably update on the transformers server so that the CLIP image encoder is not downloaded/loaded if we don't load it locally. It used to work but doesn't anymore. Let me work on local weights and will update it soon.

**Comment by zinengtang** [comment]
You can refer to this PR https://github.com/microsoft/i-Code/pull/64 
You can open a new issue if it is still not working.
