### ISSUE TITLE
Sample script for running image to audio generation?

### ISSUE THREAD

**Issue by ChloeL19** [microsoft/i-Code#49]
Thanks for this work! I'm wondering if you provide a sample script for the image to audio demo?

**Comment by ziyi-yang** [comment]
Thanks. We're working to release the model ckpt and the inference script.

**Comment by ChloeL19** [comment]
This is great to know! What's your estimated timeline on that?

**Comment by abhigoku10** [comment]
@ziyi-yang  when is the script planned to released ??

**Comment by ziyi-yang** [comment]
Hi, thanks for the interest in our work. The inference script is just merged: https://github.com/microsoft/i-Code/pull/50.
