### ISSUE TITLE
Audio decoding glitch

### ISSUE THREAD

**Issue by ZlodeiBaal** [microsoft/i-Code#57]
[audio.zip](https://github.com/microsoft/i-Code/files/11652565/audio.zip)

All generation works fine except the audio one—no matter from which data type.
It looks like there are some problems with audio decoding. Here is the output sample.

**Comment by zinengtang** [comment]
Have you loaded the audio checkpoint [CoDi_audio_diffuser_m.pth]? https://huggingface.co/ZinengTang/CoDi/tree/main
Sorry if this is not included in the jupyter notebook.

**Comment by ZlodeiBaal** [comment]
Thank you for this checkpoint!
Everything works fine now!
