### ISSUE TITLE
What dose text characters embeddings initialization weights use in UDOP pretraining?

### ISSUE THREAD

**Issue by 24-solar-terms** [microsoft/i-Code#90]
What dose text characters embeddings initialization weights use in UDOP pretraining?
Do you use some special initialization or just random initialization?
<img width="585" alt="image" src="https://github.com/microsoft/i-Code/assets/41153384/32a55915-2ab7-4f58-8398-348ecc52d43b">

**Comment by zinengtang** [comment]
We just use random initialization. The number of characters is small which is easy to learn.

**Comment by 24-solar-terms** [comment]
> We just use random initialization. The number of characters is small which is easy to learn.

@zinengtang 感谢回复，感觉如果应用在中文上会比较困难

**Comment by 24-solar-terms** [comment]
> We just use random initialization. The number of characters is small which is easy to learn.

@zinengtang 后面会有计划搞多语言的版本吗

**Comment by zinengtang** [comment]
中文的话，因为vocabulary比较小，所以可能光是字的embedding可能就够了

**Comment by 24-solar-terms** [comment]
感谢回复，不过我没太理解你这句话的意思，假如把6000个中文常用字搞成character embedding，6000的长度再加上encoder输出特征序列的长度，感觉这部分架构是不是就不太适合了

**Comment by zinengtang** [comment]
character embedding主要是更方便让模型知道每个单词长什么样，按照这个思路的话，要么模型可以多训练一下学到每个字长什么样，或者类似的可以把中文的字拆一下

**Comment by 24-solar-terms** [comment]
了解
